---
title: "CompSciX 415.2 Homework 1"
author: "Yasmin Makoui"
date: "6/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
My Github repository for my assignment can be found at this URL: [https://github.com/yasi1362/CompScix-415-2-assignments](https://github.com/yasi1362/CompScix-415-2-assignments)


```{r load_packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(mdsr)
```
Lets look at some data:

```{r}
data("WorldCities")
glimpse(WorldCities)
```
Q1 - The WorldCities data set includes 10 variables, such as:
Code, name, latitude, longitude, country, country region, population, region code, region, date.

```{r}

```


Q2 - Unique values for country region:


Q3-
WorldCities %>% country_col %>% unique()

```{r}
data("WorldCities")
WorldCities <- head(WorldCities, 200)
country_col <- WorldCities$country
unique(country_col)
```

Q4 - 

```{r}
WorldCities %>% ggplot(aes(x = population, y = region)) + ggtitle("World Region and population") + geom_histogram()
```

