---
title: "CompSciX 415.2 HW4"
author: "Yasmin Makoui"
date: "6/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Baby Names HW
```{r load_packages, warning=FALSE, message=FALSE}
#import text file
library(tidyverse)
file_path_baby_names <- '/Users/yasminmakoui/downloads/baby_names.txt'
baby_names_data <- read_delim(delim = '|', file = file_path_baby_names)

#glimpse of imported text file
glimpse(baby_names_data)

#export csv file 
write_csv(baby_names_data, path = '/Users/yasminmakoui/downloads/baby_names_two.csv')

#import csv file
file_path_baby_names_two <- '/Users/yasminmakoui/downloads/baby_names_two.csv'
baby_names_two_data <- read_csv(file = file_path_baby_names_two)

#glimpse csv file
glimpse(baby_names_two_data)
```

###Answers to section 5.6.7
#####2- 
```{r}
library(tidyverse)
library(nycflights13)
not_cancelled <- flights %>% filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% count(dest)

not_cancelled %>% count(tailnum, wt = distance)
```
#####These codes show the same results as above without using count:
```{r}
not_cancelled %>% group_by(dest) %>%
  summarise(n())

not_cancelled %>% group_by(tailnum) %>%
  summarise(sum(distance))
```

#####4- Here are the observations of cancelled flights:
```{r}
by_day <- (flights %>% mutate(cancelled = (is.na(dep_delay) | is.na(arr_delay))) %>%
  group_by(year, month, day) %>% 
  summarise(num_cancelled = sum(cancelled)))

library(ggplot2)


ggplot(data = by_day, mapping = aes(x = month, y = num_cancelled)) + 
  geom_jitter() + geom_smooth()
```

```{r}
?sort

```

###Answers to 10.5
#####1- mtcars print the row description as well
```{r}
print(mtcars)
as_tibble(mtcars)
```

#####2- 
```{r}
df <- data.frame(abc = 1, xyz = "a")
df$x
df[, "xyz"]
df[, c("abc", "xyz")]
```
```{r}
vignette("tibble")
tb <- tibble(
  `1` = "abc",
  `a` = "xyz"
)
tb
```

